---
# tasks file for web_server

- name: package installer for httpd
  package:
    name: "httpd"
    state: "present"
  register: httpd_package_status

- name: Creating Document Root Directory
  file:
    state: directory
    dest: "/var/www/apeksh"
  register: root_dir_name

- name: Configuration file for apache web server 
  template:
    dest: "/etc/httpd/conf.d/apeksh.conf"
    src: "templates/apeksh.conf.j2"
  when: httpd_package_status.rc == 0
  notify: httpd service

- name: Copy web page from url
  get_url:
    dest: "/var/www/apeksh/"
    url: "https://raw.githubusercontent.com/Apeksh742/Docker_with_Ansible/master/webPage/web.html"
  when: root_dir_name.failed == false

- name: Start httpd service
  service: 
    name: httpd
    state: started



